[gcp_service_account]
type = "service_account"
project_id = "gen-lang-client-0885226727"
private_key_id = "b1929c950c976d09ee77988439fa8254ec3d7813"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCWqSYLDnclB8fZ
+v3HuSGJNV3kIJSykcyuvy7XU1kJ4zdf8gGh1ycSY5qlNmGin3oLar6V8MejC2Gr
K5TWcfH+xv8bywG+KkomlWyLVnwByf+lTuXzwG6UVEbGKyQ/sm9iUpi6f+UNGlA8
U+4NmbFzrJ3zXbNoheR07y6oNUuDvEqy4TyAFpjurDXeCGMj9w6tKy1PSE4cZrnm
iWb6FIzYwq7lzYJBapf+g2Fr6wgPL6/YUwKRTDSUsWIas6e3AEBnhyplftFAHpMb
VOMB4YKhlTvqUzl8T9yMCZwGL+20Wa0bnsilgajpjrHUpXlf/e0QRGT8yFuIZDJV
yIa7/oxFAgMBAAECgf8gXjbOKU1vpzxImKPtRNjvoYeKe3V259wRrwFhQYbfmPFM
q7GuE4tRaBTRad2QErMlwMkxbYl2fft9yt8vM0vKcPZeAj9dm7hSkcfAJ9R8jele
mpTMyYr4UyLhcGNZS/yiIxys9M1BA2Y5j86VHXACahOFNZxV2G48sSZU/R48LuNX
VVnHk2Zl+/jSpXVB+3r6MdxaLSQ77hWGCYAkg9qyW8ZK61fyoI9JUK55e4X4uPw3
bQZc669+trZNSWOKhalJl9LGQ+EJIkqgdxfTlPrPlwBhxPYJAB+IKRVz3PYYnhrJ
8jPO0PEaSXFbCPeCj28ZTEppQskGu8TMR2a0v0ECgYEAz/BiYaO2Lundnn4rrB4M
AL4MlHea5sB1VZ9cy35gU9oaIG9q1FAevDKwhiDvNyIvjcitKUgRo3X5YluC4pxg
GzV2O2fM+F/4M9XZL7OkrQMPCQDHTq69/DsIfQa8vcgbWRHu5yq3Cqfm1/0d+6Ux
cTR+VndrrfLWzcQpBqemBPECgYEAuXulho2Xbssp9Vz7/Umvw6YoqOofeBEjHFk6
dWkDXT7U6IXGHkU24NpepGrNR9SVR5S3V/ELy7HOTs0o5nzJGB5DnicsemJqqtuP
n1RnoJc38eFNz8kYHwCOi9p16ktLW3SBYEwo38w6QefsY+uLlLfI5fvQIJxya2eC
pWLIbJUCgYBbwKBIoSpkbQFDTD0NB30YXsPCRzxskYO0sksJ58utdFGO+lrTMD8/
n8ZQiPvFAiqlj2UJECnoTMgr5GFOiN3HY8G12MmS1xX4GWZqLAR/6xeZS2SmjWh7
gbjvIifqPgADP2yBSFHYO9oaeC/guDWm1BjjInK7IKozxVis/RC+oQKBgH0yZIvp
zqlOIMgpNz3EGwtogFFjllIo3xYndDoD4+1wl61Lfmq4NU6YlwFLxbwSVaC3VPnb
DiczoRm3iT/qQqIw61s4/eCtxWoGQW8+PaQ77dsqRKdYCRwD+DOWBblbkUXt4dXq
EjzdUQVjUkAvoUuEsenqipU4hFLSz3BquPXxAoGAFshmrefubsKF6OPhATMYJhPu
GTJD047qiG2DFJSCImkf9/XwExjKayThCM7JmBY5LBIc9zt3vqz37a5nqb0nmpSk
z0CQRukQv5A3tVh2XaCooz+MoMdPxVpWL+TrnSXqGfzpQARKj02TzHWLb2JL4GzE
VzuyxcEng545++wZ8ag=
-----END PRIVATE KEY-----"""
client_email = "streamlit-ankor-checker@gen-lang-client-0885226727.iam.gserviceaccount.com"
client_id = "104324408873365771661"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-ankor-checker%40gen-lang-client-0885226727.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1uYdXig64LwnwLgWc-ujIOTjP166iMpi4U5y2-0sL1cI/edit"